# Generated by Django 5.2.8 on 2025-11-06 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('MUSIQUE', 'Musique'), ('BUSINESS', 'Business'), ('GASTRONOMIE', 'Gastronomie'), ('SPORT', 'Sport'), ('CULTURE', 'Culture')], max_length=20, verbose_name='Catégorie')),
                ('date', models.DateTimeField(verbose_name='Date et heure')),
                ('location', models.CharField(max_length=200, verbose_name='Lieu')),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacité maximale')),
                ('available_seats', models.IntegerField(verbose_name='Places disponibles')),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par personne (€)')),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente de validation'), ('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé'), ('TERMINE', 'Terminé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('image_url', models.URLField(blank=True, verbose_name="URL de l'image")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['date'],
            },
        ),
    ]
