# Generated by Django 5.2.8 on 2025-11-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par personne (TND)'),
        ),
    ]
