# Generated by Django 5.2.8 on 2025-11-17 10:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_price_per_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note (1-5 étoiles)')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la recommandation')),
                ('comment', models.TextField(verbose_name='Commentaire')),
                ('organization_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Organisation')),
                ('ambiance_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Ambiance')),
                ('value_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rapport qualité/prix')),
                ('venue_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Lieu/Emplacement')),
                ('would_recommend', models.BooleanField(default=True, verbose_name='Je recommande cet événement')),
                ('tags', models.CharField(blank=True, help_text='Mots-clés séparés par des virgules (ex: convivial, familial, professionnel)', max_length=500, verbose_name='Mots-clés')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name="Nombre de votes 'Utile'")),
                ('is_approved', models.BooleanField(default=True, verbose_name='Approuvé')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mise en avant')),
                ('admin_response', models.TextField(blank=True, verbose_name="Réponse de l'administrateur")),
                ('photo_url', models.URLField(blank=True, verbose_name='Photo (URL)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='events.event', verbose_name='Événement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Recommandation d'événement",
                'verbose_name_plural': "Recommandations d'événements",
                'ordering': ['-created_at'],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='events.eventrecommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Vote 'Utile'",
                'verbose_name_plural': "Votes 'Utile'",
                'unique_together': {('recommendation', 'user')},
            },
        ),
    ]
