# Generated by Django 5.2.8 on 2025-11-10 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_alter_event_price_per_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de contrat')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du contrat')),
                ('contract_type', models.CharField(choices=[('SERVICE', 'Contrat de service'), ('PARTNERSHIP', 'Partenariat'), ('SPONSORSHIP', 'Sponsoring'), ('VENUE', 'Location de lieu'), ('SUPPLIER', 'Fournisseur'), ('OTHER', 'Autre')], max_length=20, verbose_name='Type de contrat')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nom du client/partenaire')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email du client')),
                ('client_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du client')),
                ('client_address', models.TextField(blank=True, verbose_name='Adresse du client')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Montant (TND)')),
                ('terms', models.TextField(verbose_name='Conditions du contrat')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING', 'En attente'), ('ACTIVE', 'Actif'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('signed_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de signature')),
                ('signed_by_client', models.BooleanField(default=False, verbose_name='Signé par le client')),
                ('signed_by_admin', models.BooleanField(default=False, verbose_name="Signé par l'administrateur")),
                ('client_signature', models.TextField(blank=True, verbose_name='Signature client (base64)')),
                ('admin_signature', models.TextField(blank=True, verbose_name='Signature admin (base64)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='events.event', verbose_name='Événement associé')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-created_at'],
            },
        ),
    ]
