# Generated by Django 5.2.8 on 2025-11-06 20:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seats', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de places')),
                ('status', models.CharField(choices=[('CONFIRMEE', 'Confirmée'), ('EN_ATTENTE', 'En attente'), ('ANNULEE', 'Annulée')], default='CONFIRMEE', max_length=20, verbose_name='Statut')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix total (€)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payé')),
                ('reservation_code', models.CharField(max_length=20, unique=True, verbose_name='Code de réservation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Annulée le')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='events.event', verbose_name='Événement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Participant')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='reservation_user_id_b23f11_idx'), models.Index(fields=['event', 'status'], name='reservation_event_i_21178d_idx')],
            },
        ),
    ]
