# Generated by Django 5.2.8 on 2025-11-10 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_alter_event_price_per_person'),
        ('reservations', '0002_alter_reservation_total_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RESERVATION', 'Problème de réservation'), ('EVENT', "Problème d'événement"), ('PAYMENT', 'Problème de paiement'), ('SERVICE', 'Qualité de service'), ('TECHNICAL', 'Problème technique'), ('OTHER', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('status', models.CharField(choices=[('NEW', 'Nouvelle'), ('IN_PROGRESS', 'En cours de traitement'), ('RESOLVED', 'Résolue'), ('CLOSED', 'Fermée')], default='NEW', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('LOW', 'Basse'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=20, verbose_name='Priorité')),
                ('admin_response', models.TextField(blank=True, verbose_name="Réponse de l'administrateur")),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Répondu le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolue le')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event', verbose_name='Événement concerné')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.reservation', verbose_name='Réservation concernée')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_responses', to=settings.AUTH_USER_MODEL, verbose_name='Répondu par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'ordering': ['-created_at'],
            },
        ),
    ]
