# Generated by Django 5.2.8 on 2025-11-10 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du lieu')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('location_type', models.CharField(choices=[('INDOOR', 'Intérieur'), ('OUTDOOR', 'Extérieur'), ('HYBRID', 'Hybride')], default='INDOOR', max_length=20, verbose_name='Type de lieu')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacité maximale')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Surface (m²)')),
                ('hourly_rate', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Tarif horaire (TND)')),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Tarif journalier (TND)')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('OCCUPIED', 'Occupé'), ('MAINTENANCE', 'En maintenance'), ('UNAVAILABLE', 'Indisponible')], default='AVAILABLE', max_length=20, verbose_name='Statut')),
                ('amenities', models.TextField(blank=True, verbose_name='Équipements disponibles')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Personne de contact')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone de contact')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_locations', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Lieu',
                'verbose_name_plural': 'Lieux',
                'ordering': ['name'],
            },
        ),
    ]
