# Generated by Django 5.2.8 on 2025-11-11 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='governorate',
            field=models.CharField(choices=[('TUNIS', 'Tunis'), ('ARIANA', 'Ariana'), ('BEN_AROUS', 'Ben Arous'), ('MANOUBA', 'Manouba'), ('NABEUL', 'Nabeul'), ('ZAGHOUAN', 'Zaghouan'), ('BIZERTE', 'Bizerte'), ('BEJA', 'Béja'), ('JENDOUBA', 'Jendouba'), ('KEF', 'Le Kef'), ('SILIANA', 'Siliana'), ('SOUSSE', 'Sousse'), ('MONASTIR', 'Monastir'), ('MAHDIA', 'Mahdia'), ('SFAX', 'Sfax'), ('KAIROUAN', 'Kairouan'), ('KASSERINE', 'Kasserine'), ('SIDI_BOUZID', 'Sidi Bouzid'), ('GABES', 'Gabès'), ('MEDENINE', 'Médenine'), ('TATAOUINE', 'Tataouine'), ('GAFSA', 'Gafsa'), ('TOZEUR', 'Tozeur'), ('KEBILI', 'Kébili')], default='TUNIS', max_length=20, verbose_name='Gouvernorat'),
        ),
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date bloquée')),
                ('reason', models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('PRIVATE_EVENT', 'Événement privé'), ('RENOVATION', 'Rénovation'), ('HOLIDAY', 'Jour férié'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Raison')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='locations.location', verbose_name='Lieu')),
            ],
            options={
                'verbose_name': 'Date bloquée',
                'verbose_name_plural': 'Dates bloquées',
                'ordering': ['date'],
                'unique_together': {('location', 'date')},
            },
        ),
    ]
